volumes:
  mongo-data:
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webhook-workers
      - mongodb-database
      - redis-broker
    # network_mode: host
    image: flask-webhook-app
    env_file:
      - .env.docker
    ports:
      - "3000:5000"
  webhook-workers:
    build:
      context: .
      dockerfile: Dockerfile.celery
    image: celery-webhook-workers
    environment:
      - C_FORCE_ROOT='true'
    env_file:
      - .env.docker
    depends_on:
      - mongodb-database
      - redis-broker
  mongodb-database:
    # network_mode: host
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  redis-broker:
    # network_mode: host
    image: redis:latest
